In [7]:
import numpy as np
import pandas as pd

stocks = pd.read_excel("data-DJ30-july2011-june2013.xlsx")
stocks = stocks.sort_values(by = 'Date')
stocks = stocks.reset_index()
stocks = stocks.drop('index', axis = 1)
stocks

Date    AXP    BAC    JPM   CSCO    HPQ     IBM   INTC   MSFT
0   2011-07-01  50.91  10.98  39.22  15.10  35.25  167.88  20.75  24.41
1   2011-07-05  51.62  10.60  38.43  15.04  34.66  169.75  21.26  25.25
2   2011-07-11  50.39   9.90  37.71  14.90  33.38  168.84  20.60  25.12
3   2011-07-18  50.81  10.03  39.79  15.73  34.92  178.11  21.30  25.82
4   2011-07-25  48.67   9.62  38.15  15.26  33.46  174.91  20.56  25.70
..         ...    ...    ...    ...    ...    ...     ...    ...    ...
100 2013-05-28  75.48  13.65  54.19  23.95  24.28  206.99  24.04  34.66
101 2013-06-03  77.80  13.38  53.88  24.32  24.66  205.32  24.35  35.42
102 2013-06-10  72.75  13.07  52.75  23.92  24.74  201.19  24.68  34.16
103 2013-06-17  73.09  12.69  51.58  24.31  24.15  194.49  23.97  33.04
104 2013-06-24  74.53  12.86  52.41  24.17  24.80  190.16  24.00  34.30

[105 rows x 9 columns]

In [8]:
column_names = stocks.columns.values.tolist()
for company in column_names[1:]:
    stocks[company+' Weekly Return'] = 0
    
    
for company in column_names[1:]:
    for i in range(1, 105):
        stocks[company+' Weekly Return'][i] = (stocks[company][i] - stocks[company][i- 1])/stocks[company][i- 1]
stocks = stocks.drop(index = 0)
stocks

<ipython-input-8-6daf052795f2>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stocks[company+' Weekly Return'][i] = (stocks[company][i] - stocks[company][i- 1])/stocks[company][i- 1]


Date    AXP    BAC    JPM   CSCO    HPQ     IBM   INTC   MSFT  \
1   2011-07-05  51.62  10.60  38.43  15.04  34.66  169.75  21.26  25.25   
2   2011-07-11  50.39   9.90  37.71  14.90  33.38  168.84  20.60  25.12   
3   2011-07-18  50.81  10.03  39.79  15.73  34.92  178.11  21.30  25.82   
4   2011-07-25  48.67   9.62  38.15  15.26  33.46  174.91  20.56  25.70   
5   2011-08-01  45.92   8.09  35.46  14.27  31.04  166.38  19.33  24.09   
..         ...    ...    ...    ...    ...    ...     ...    ...    ...   
100 2013-05-28  75.48  13.65  54.19  23.95  24.28  206.99  24.04  34.66   
101 2013-06-03  77.80  13.38  53.88  24.32  24.66  205.32  24.35  35.42   
102 2013-06-10  72.75  13.07  52.75  23.92  24.74  201.19  24.68  34.16   
103 2013-06-17  73.09  12.69  51.58  24.31  24.15  194.49  23.97  33.04   
104 2013-06-24  74.53  12.86  52.41  24.17  24.80  190.16  24.00  34.30   

     AXP Weekly Return  BAC Weekly Return  JPM Weekly Return  \
1             0.013946          -0.034608          -0.020143   
2            -0.023828          -0.066038          -0.018735   
3             0.008335           0.013131           0.055158   
4            -0.042118          -0.040877          -0.041216   
5            -0.056503          -0.159044          -0.070511   
..                 ...                ...                ...   
100           0.005864           0.031746           0.017271   
101           0.030737          -0.019780          -0.005721   
102          -0.064910          -0.023169          -0.020973   
103           0.004674          -0.029074          -0.022180   
104           0.019702           0.013396           0.016092   

     CSCO Weekly Return  HPQ Weekly Return  IBM Weekly Return  \
1             -0.003974          -0.016738           0.011139   
2             -0.009309          -0.036930          -0.005361   
3              0.055705           0.046135           0.054904   
4             -0.029879          -0.041810          -0.017966   
5             -0.064875          -0.072325          -0.048768   
..                  ...                ...                ...   
100            0.024818           0.008725           0.011187   
101            0.015449           0.015651          -0.008068   
102           -0.016447           0.003244          -0.020115   
103            0.016304          -0.023848          -0.033302   
104           -0.005759           0.026915          -0.022263   

     INTC Weekly Return  MSFT Weekly Return  
1              0.024578            0.034412  
2             -0.031044           -0.005149  
3              0.033981            0.027866  
4             -0.034742           -0.004648  
5             -0.059825           -0.062646  
..                  ...                 ...  
100            0.014774            0.018513  
101            0.012895            0.021927  
102            0.013552           -0.035573  
103           -0.028768           -0.032787  
104            0.001252            0.038136  

[104 rows x 17 columns]

In [9]:
for company in column_names[1:]:
    stocks[company+' Mean Return'] = stocks.loc[:, company+' Weekly Return'].mean()
for company in column_names[1:]:
    stocks[company+' Demeaned'] = stocks[company+' Weekly Return'] - stocks[company+' Mean Return']
stocks

Date    AXP    BAC    JPM   CSCO    HPQ     IBM   INTC   MSFT  \
1   2011-07-05  51.62  10.60  38.43  15.04  34.66  169.75  21.26  25.25   
2   2011-07-11  50.39   9.90  37.71  14.90  33.38  168.84  20.60  25.12   
3   2011-07-18  50.81  10.03  39.79  15.73  34.92  178.11  21.30  25.82   
4   2011-07-25  48.67   9.62  38.15  15.26  33.46  174.91  20.56  25.70   
5   2011-08-01  45.92   8.09  35.46  14.27  31.04  166.38  19.33  24.09   
..         ...    ...    ...    ...    ...    ...     ...    ...    ...   
100 2013-05-28  75.48  13.65  54.19  23.95  24.28  206.99  24.04  34.66   
101 2013-06-03  77.80  13.38  53.88  24.32  24.66  205.32  24.35  35.42   
102 2013-06-10  72.75  13.07  52.75  23.92  24.74  201.19  24.68  34.16   
103 2013-06-17  73.09  12.69  51.58  24.31  24.15  194.49  23.97  33.04   
104 2013-06-24  74.53  12.86  52.41  24.17  24.80  190.16  24.00  34.30   

     AXP Weekly Return  ...  INTC Mean Return  MSFT Mean Return  AXP Demeaned  \
1             0.013946  ...          0.001929          0.003731      0.009762   
2            -0.023828  ...          0.001929          0.003731     -0.028013   
3             0.008335  ...          0.001929          0.003731      0.004150   
4            -0.042118  ...          0.001929          0.003731     -0.046302   
5            -0.056503  ...          0.001929          0.003731     -0.060688   
..                 ...  ...               ...               ...           ...   
100           0.005864  ...          0.001929          0.003731      0.001679   
101           0.030737  ...          0.001929          0.003731      0.026552   
102          -0.064910  ...          0.001929          0.003731     -0.069095   
103           0.004674  ...          0.001929          0.003731      0.000489   
104           0.019702  ...          0.001929          0.003731      0.015517   

     BAC Demeaned  JPM Demeaned  CSCO Demeaned  HPQ Demeaned  IBM Demeaned  \
1       -0.037916     -0.023898      -0.009244     -0.015095      0.009512   
2       -0.069346     -0.022491      -0.014579     -0.035287     -0.006987   
3        0.009823      0.051402       0.050434      0.047778      0.053277   
4       -0.044185     -0.044972      -0.035149     -0.040167     -0.019593   
5       -0.162352     -0.074267      -0.070146     -0.070682     -0.050395   
..            ...           ...            ...           ...           ...   
100      0.028438      0.013515       0.019548      0.010367      0.009561   
101     -0.023088     -0.009476       0.010179      0.017294     -0.009695   
102     -0.026477     -0.024728      -0.021718      0.004887     -0.021742   
103     -0.032382     -0.025936       0.011034     -0.022205     -0.034928   
104      0.010088      0.012336      -0.011029      0.028558     -0.023890   

     INTC Demeaned  MSFT Demeaned  
1         0.022649       0.030682  
2        -0.032974      -0.008879  
3         0.032051       0.024136  
4        -0.036671      -0.008378  
5        -0.061754      -0.066376  
..             ...            ...  
100       0.012845       0.014782  
101       0.010966       0.018197  
102       0.011623      -0.039304  
103      -0.030698      -0.036517  
104      -0.000678       0.034405  

[104 rows x 33 columns]

AXP Demeaned  BAC Demeaned  JPM Demeaned  CSCO Demeaned  HPQ Demeaned  \
1       -0.018351     -0.012327     -0.014811       0.007360     -0.023975   
2       -0.003681      0.030837      0.023709      -0.014475      0.026666   
3        0.070386      0.024611      0.022448       0.018290     -0.000998   
4       -0.028850      0.021072      0.006780      -0.013647     -0.013174   
5       -0.004859     -0.029877     -0.015951      -0.022650     -0.006414   
..            ...           ...           ...            ...           ...   
100      0.000970      0.000892      0.001026       0.001567      0.002235   
101      0.000970      0.000892      0.001026       0.001567      0.002235   
102      0.000970      0.000892      0.001026       0.001567      0.002235   
103      0.000970      0.000892      0.001026       0.001567      0.002235   
104      0.000970      0.000892      0.001026       0.001567      0.002235   

     IBM Demeaned  INTC Demeaned  MSFT Demeaned  
1        0.022843      -0.000447      -0.035323  
2        0.034522       0.030424       0.035310  
3        0.020601      -0.012568       0.038297  
4        0.008206      -0.011928      -0.020045  
5       -0.010991      -0.013756      -0.016765  
..            ...            ...            ...  
100      0.000073       0.000803       0.001412  
101      0.000073       0.000803       0.001412  
102      0.000073       0.000803       0.001412  
103      0.000073       0.000803       0.001412  
104      0.000073       0.000803       0.001412  

[104 rows x 8 columns]

In [10]:
#calculate the covariance matrix
T_bar = np.matrix(stocks.iloc[:, -8:])
cov_matrix = (1/103)*np.dot(np.transpose(T_bar), T_bar)
np.set_printoptions(suppress=True)
cov_matrix

matrix([[0.00103891, 0.00133579, 0.0009931 , 0.00046476, 0.00067442,
         0.00045827, 0.0005586 , 0.00053707],
        [0.00133579, 0.003634  , 0.002142  , 0.00097133, 0.00113774,
         0.00086241, 0.00089222, 0.00087223],
        [0.0009931 , 0.002142  , 0.00193987, 0.00092209, 0.00109858,
         0.00068968, 0.00069977, 0.0006791 ],
        [0.00046476, 0.00097133, 0.00092209, 0.00149673, 0.00089824,
         0.0005881 , 0.00053646, 0.00053559],
        [0.00067442, 0.00113774, 0.00109858, 0.00089824, 0.00336519,
         0.00084015, 0.0009772 , 0.00056829],
        [0.00045827, 0.00086241, 0.00068968, 0.0005881 , 0.00084015,
         0.00086074, 0.00052677, 0.00043336],
        [0.0005586 , 0.00089222, 0.00069977, 0.00053646, 0.0009772 ,
         0.00052677, 0.00107369, 0.00051065],
        [0.00053707, 0.00087223, 0.0006791 , 0.00053559, 0.00056829,
         0.00043336, 0.00051065, 0.00091968]])

In [5]:
stocks2 = pd.read_excel("indeces-jul26-aug9-2012.xlsx")
stocks2

Date  Dow Jones  NASDAQ   S&P 500
0  2012-07-26   12887.93  2893.25  1360.02
1  2012-07-27   13075.66  2958.09  1385.97
2  2012-07-30   13073.01  2945.84  1385.30
3  2012-07-31   13008.68  2939.52  1379.32
4  2012-08-01   12976.13  2920.21  1375.32
5  2012-08-02   12878.88  2909.77  1365.00
6  2012-08-03   13096.17  2967.90  1390.99
7  2012-08-06   13117.51  2989.91  1394.23
8  2012-08-07   13168.60  3015.86  1401.35
9  2012-08-08   13175.64  3011.25  1402.22
10 2012-08-09   13165.19  3018.64  1402.80

In [6]:
column_names2 = stocks2.columns.values.tolist()
for company in column_names2[1:]:
    stocks2[company+' Daily Return'] = 0
    
    
for company in column_names2[1:]:
    for i in range(1, 11):
        stocks2[company+' Daily Return'][i] = np.log((stocks2[company][i]/stocks2[company][i- 1]))
stocks2 = stocks2.drop(index = 0)
stocks2

<ipython-input-6-a3244e4dbf00>:8: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stocks2[company+' Daily Return'][i] = np.log((stocks2[company][i]/stocks2[company][i- 1]))


Date  Dow Jones  NASDAQ   S&P 500  Dow Jones Daily Return  \
1  2012-07-27   13075.66  2958.09  1385.97                0.014461   
2  2012-07-30   13073.01  2945.84  1385.30               -0.000203   
3  2012-07-31   13008.68  2939.52  1379.32               -0.004933   
4  2012-08-01   12976.13  2920.21  1375.32               -0.002505   
5  2012-08-02   12878.88  2909.77  1365.00               -0.007523   
6  2012-08-03   13096.17  2967.90  1390.99                0.016731   
7  2012-08-06   13117.51  2989.91  1394.23                0.001628   
8  2012-08-07   13168.60  3015.86  1401.35                0.003887   
9  2012-08-08   13175.64  3011.25  1402.22                0.000534   
10 2012-08-09   13165.19  3018.64  1402.80               -0.000793   

    NASDAQ  Daily Return  S&P 500 Daily Return  
1               0.022163              0.018901  
2              -0.004150             -0.000484  
3              -0.002148             -0.004326  
4              -0.006591             -0.002904  
5              -0.003581             -0.007532  
6               0.019781              0.018861  
7               0.007389              0.002327  
8               0.008642              0.005094  
9              -0.001530              0.000621  
10              0.002451              0.000414

In [7]:
for company in column_names2[1:]:
    stocks2[company+' Mean Return'] = stocks2.loc[:, company+' Daily Return'].mean()


for company in column_names2[1:]:
    stocks2[company+' Demeaned'] = stocks2[company+' Daily Return'] - stocks2[company+' Mean Return']
stocks2

Date  Dow Jones  NASDAQ   S&P 500  Dow Jones Daily Return  \
1  2012-07-27   13075.66  2958.09  1385.97                0.014461   
2  2012-07-30   13073.01  2945.84  1385.30               -0.000203   
3  2012-07-31   13008.68  2939.52  1379.32               -0.004933   
4  2012-08-01   12976.13  2920.21  1375.32               -0.002505   
5  2012-08-02   12878.88  2909.77  1365.00               -0.007523   
6  2012-08-03   13096.17  2967.90  1390.99                0.016731   
7  2012-08-06   13117.51  2989.91  1394.23                0.001628   
8  2012-08-07   13168.60  3015.86  1401.35                0.003887   
9  2012-08-08   13175.64  3011.25  1402.22                0.000534   
10 2012-08-09   13165.19  3018.64  1402.80               -0.000793   

    NASDAQ  Daily Return  S&P 500 Daily Return  Dow Jones Mean Return  \
1               0.022163              0.018901               0.002129   
2              -0.004150             -0.000484               0.002129   
3              -0.002148             -0.004326               0.002129   
4              -0.006591             -0.002904               0.002129   
5              -0.003581             -0.007532               0.002129   
6               0.019781              0.018861               0.002129   
7               0.007389              0.002327               0.002129   
8               0.008642              0.005094               0.002129   
9              -0.001530              0.000621               0.002129   
10              0.002451              0.000414               0.002129   

    NASDAQ  Mean Return  S&P 500 Mean Return  Dow Jones Demeaned  \
1              0.004243             0.003097            0.012333   
2              0.004243             0.003097           -0.002331   
3              0.004243             0.003097           -0.007061   
4              0.004243             0.003097           -0.004634   
5              0.004243             0.003097           -0.009651   
6              0.004243             0.003097            0.014603   
7              0.004243             0.003097           -0.000500   
8              0.004243             0.003097            0.001759   
9              0.004243             0.003097           -0.001594   
10             0.004243             0.003097           -0.002922   

    NASDAQ  Demeaned  S&P 500 Demeaned  
1           0.017921          0.015804  
2          -0.008392         -0.003581  
3          -0.006390         -0.007423  
4          -0.010833         -0.006001  
5          -0.007824         -0.010629  
6           0.015538          0.015764  
7           0.003146         -0.000771  
8           0.004399          0.001997  
9          -0.005772         -0.002476  
10         -0.001791         -0.002684

In [8]:
#covariance matrix of log returns
T_bar2 = np.matrix(stocks2.iloc[:, 10:13])
cov_matrix2 = (1/9)*np.dot(np.transpose(T_bar2), T_bar2)
np.set_printoptions(suppress=True)
cov_matrix2

matrix([[0.00006107, 0.00007321, 0.00007022],
        [0.00007321, 0.00010202, 0.00008659],
        [0.00007022, 0.00008659, 0.00008146]])

In [9]:
#covariance and correlation matrix 
indices = pd.read_excel("indices-july2011.xlsx")
indices

Date  CCMP Index  INDU Index  TRAN Index  UTIL Index  NYA Index  \
0   2010-12-31     2652.87    11577.51     5106.75      404.99    7964.02   
1   2011-01-03     2691.52    11670.75     5174.93      406.58    8043.97   
2   2011-01-04     2681.25    11691.18     5139.00      408.52    8022.18   
3   2011-01-05     2702.20    11722.89     5154.59      406.20    8040.04   
4   2011-01-06     2709.89    11697.31     5143.97      406.43    8000.90   
..         ...         ...         ...         ...         ...        ...   
139 2011-07-21     2834.43    12724.41     5432.26      441.33    8411.45   
140 2011-07-22     2858.83    12681.16     5428.24      439.23    8408.20   
141 2011-07-25     2842.80    12592.80     5414.43      440.09    8357.57   
142 2011-07-26     2839.96    12501.30     5341.89      438.62    8331.67   
143 2011-07-27     2764.79    12302.55     5204.35      438.14    8153.21   

     SPX Index  OEX Index  XAX Index  OMX Index  
0      1257.64     565.90    2208.38    1176.85  
1      1271.87     572.23    2217.62    1176.85  
2      1270.20     573.23    2198.58    1165.88  
3      1276.56     576.00    2200.51    1151.80  
4      1273.85     574.73    2172.91    1151.80  
..         ...        ...        ...        ...  
139    1343.80     601.89    2439.69    1088.16  
140    1345.02     602.51    2450.01    1091.00  
141    1337.43     599.41    2444.65    1086.38  
142    1331.94     596.88    2456.14    1078.13  
143    1304.89     586.18    2408.79    1070.50  

[144 rows x 10 columns]

In [10]:
log_return = indices.iloc[:, 1:].apply(lambda col: (col - col.shift(1))/col.shift(1))
log_return

CCMP Index  INDU Index  TRAN Index  UTIL Index  NYA Index  SPX Index  \
0           NaN         NaN         NaN         NaN        NaN        NaN   
1      0.014569    0.008054    0.013351    0.003926   0.010039   0.011315   
2     -0.003816    0.001751   -0.006943    0.004772  -0.002709  -0.001313   
3      0.007814    0.002712    0.003034   -0.005679   0.002226   0.005007   
4      0.002846   -0.002182   -0.002060    0.000566  -0.004868  -0.002123   
..          ...         ...         ...         ...        ...        ...   
139    0.007178    0.012130    0.016715    0.015462   0.015651   0.013546   
140    0.008608   -0.003399   -0.000740   -0.004758  -0.000386   0.000908   
141   -0.005607   -0.006968   -0.002544    0.001958  -0.006022  -0.005643   
142   -0.000999   -0.007266   -0.013398   -0.003340  -0.003099  -0.004105   
143   -0.026469   -0.015898   -0.025747   -0.001094  -0.021419  -0.020309   

     OEX Index  XAX Index  OMX Index  
0          NaN        NaN        NaN  
1     0.011186   0.004184   0.000000  
2     0.001748  -0.008586  -0.009321  
3     0.004832   0.000878  -0.012077  
4    -0.002205  -0.012543   0.000000  
..         ...        ...        ...  
139   0.013897   0.015915  -0.004965  
140   0.001030   0.004230   0.002610  
141  -0.005145  -0.002188  -0.004235  
142  -0.004221   0.004700  -0.007594  
143  -0.017927  -0.019278  -0.007077  

[144 rows x 9 columns]

In [11]:
#mean normalized returns
mean_ret = log_return.apply(lambda col: col - col.mean()).dropna().values
mean_ret

array([[ 0.01423032,  0.00759975,  0.01315083, ...,  0.01090704,
         0.00352474,  0.00060704],
       [-0.00415449,  0.00129674, -0.00714321, ...,  0.00146887,
        -0.00924511, -0.00871446],
       [ 0.00747472,  0.00225851,  0.00283354, ...,  0.00455358,
         0.00021851, -0.01146968],
       ...,
       [-0.00594599, -0.00742161, -0.00274423, ..., -0.00542382,
        -0.00284707, -0.00362761],
       [-0.00133782, -0.00771985, -0.01359765, ..., -0.0044995 ,
         0.00404073, -0.00698699],
       [-0.02680749, -0.01635214, -0.02594756, ..., -0.01820523,
        -0.01993754, -0.00647003]])

In [12]:
#covariance matrix
cov_indices = (1/142)*np.dot(np.transpose(mean_ret), mean_ret)
cov_indices

array([[0.00010004, 0.00006704, 0.00009667, 0.00004004, 0.00008277,
        0.0000789 , 0.00007435, 0.00007111, 0.00005456],
       [0.00006704, 0.00005816, 0.00007129, 0.00003801, 0.00006529,
        0.00006138, 0.00005963, 0.00005287, 0.00004199],
       [0.00009667, 0.00007129, 0.00013588, 0.00004536, 0.00008615,
        0.00008305, 0.00007746, 0.00006015, 0.00005746],
       [0.00004004, 0.00003801, 0.00004536, 0.00004484, 0.0000432 ,
        0.0000401 , 0.00003937, 0.0000346 , 0.00003043],
       [0.00008277, 0.00006529, 0.00008615, 0.0000432 , 0.00008237,
        0.00007446, 0.00007137, 0.00007305, 0.00005401],
       [0.0000789 , 0.00006138, 0.00008305, 0.0000401 , 0.00007446,
        0.00006977, 0.00006694, 0.0000618 , 0.00004655],
       [0.00007435, 0.00005963, 0.00007746, 0.00003937, 0.00007137,
        0.00006694, 0.00006517, 0.00005866, 0.00004366],
       [0.00007111, 0.00005287, 0.00006015, 0.0000346 , 0.00007305,
        0.0000618 , 0.00005866, 0.00010396, 0.00005001],


In [14]:
#correlation matrix
log_return = log_return.dropna()
corr_ret = np.corrcoef(log_return, rowvar = False)
corr_ret

array([[1.        , 0.87895419, 0.82920437, 0.59789591, 0.9117825 ,
        0.94442799, 0.92084117, 0.69724286, 0.51809119],
       [0.87895419, 1.        , 0.80188442, 0.74435801, 0.9433075 ,
        0.96344442, 0.96858557, 0.67987108, 0.52291232],
       [0.82920437, 0.80188442, 1.        , 0.58117336, 0.81431119,
        0.85294819, 0.8231948 , 0.50605761, 0.46818928],
       [0.59789591, 0.74435801, 0.58117336, 1.        , 0.71086699,
        0.7169004 , 0.72820159, 0.5067486 , 0.43160067],
       [0.9117825 , 0.9433075 , 0.81431119, 0.71086699, 1.        ,
        0.98213454, 0.97417029, 0.78938373, 0.56521924],
       [0.94442799, 0.96344442, 0.85294819, 0.7169004 , 0.98213454,
        1.        , 0.99273161, 0.72560793, 0.52927191],
       [0.92084117, 0.96858557, 0.8231948 , 0.72820159, 0.97417029,
        0.99273161, 1.        , 0.71263004, 0.51366332],
       [0.69724286, 0.67987108, 0.50605761, 0.5067486 , 0.78938373,
        0.72560793, 0.71263004, 1.        , 0.46585687],
