In [17]:
import numpy as np
import pandas as pd

from scipy.linalg import cholesky
def linear_solve_cholesky(A, b):
    U = cholesky(A)
    y = np.linalg.solve(np.transpose(U), b)
    x = np.linalg.solve(U, y)
    return x 

def minvar(covmatrix, returns, rf, e_returns):
    n = len(returns)
    ones = np.ones((n, 1))
    miu_bar = returns - np.dot(rf, ones)
    x = linear_solve_cholesky(covmatrix, miu_bar)
    wmin = ((e_returns - rf)/np.dot(np.transpose(miu_bar), x))*x
    wmin_cash = 1 - np.dot(np.transpose(ones), wmin)
    sigma_min = np.sqrt(np.dot(np.dot(np.transpose(wmin), covmatrix), wmin))
    return wmin, wmin_cash, sigma_min
    

In [18]:
#Chapter9 Problem6
returns = [[0.06],
          [0.09],
          [0.12]]

risk_free_rate = 0.03
e_returns = 0.1
covmatrix = [[0.0324, -0.0180, 0.0065], [-0.0180, 0.0400, -0.0120], [0.0065, -0.0120, 0.0576]]
wmin, wmin_cash, sigma = minvar(covmatrix, returns, risk_free_rate, e_returns)
wmin_cash

array([[-0.19136369]])

In [19]:
sigma

array([[0.10678676]])

In [21]:
def minvar_fromtangency(covmatrix, returns, rf, e_returns):
    n = len(returns)
    ones = np.ones((n, 1))
    miu_bar = returns - np.dot(rf, ones)
    x = linear_solve_cholesky(covmatrix, miu_bar)
    w_tangency = (1/np.dot(np.transpose(ones), x))*x
    wmin_cash = 1 - (e_returns - rf)/np.dot(np.transpose(miu_bar), w_tangency)
    wmin = (1 - wmin_cash)*w_tangency
    sigma_min = np.sqrt(np.dot(np.dot(np.transpose(wmin), covmatrix), wmin))
    return wmin, wmin_cash, sigma_min, w_tangency
    
wmin, wmin_cash, sigma, tangency = minvar_fromtangency(covmatrix, returns, risk_free_rate, e_returns)
tangency

array([[0.30865076],
       [0.42415856],
       [0.26719068]])

In [22]:
wmin_cash

array([[-0.19136369]])